### ISSUE TITLE
ABI Branch

### ISSUE THREAD

**Issue by BrianGuo** [CornellBlockchain/ethereumbook#6]
@ohadh123 @cosmoviola  sorry for putting the info on the slack as opposed to the github repo. Figured people would check it more if it was on the slack.

Let me know when the issues I mentioned on the slack are fixed and pulled up with Andreas

Also, include Cornell Blockchain on the contributors list

**Comment by ohadh123** [comment]
Fixed the clarity of the paragraph and the typo. Also looks like @LucasSwitz added Cornell Blockchain as a contributor in his latest PR so we should be good
